### ISSUE TITLE
[BUG] Annotation Tool broken on categorization page on neurobagel.org

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/annotation_tool#471] opened 2023-06-21 15:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Users should be able to categorize columns of their uploaded participants.tsv and proceed from the categorization page to the annotation page

### Current Behavior

The version of the annotation tool currently on `annotate.neurobagel.org` is broken once reaching the categorization page.

Coloring of the category select table and column linking table is absent and the column linking table's rows are no longer clickable.

This blocks proceeding to the annotation page.

The tool functions locally via `npm run dev` and all e2e/component tests are green.

### Error message

![Screen Shot 2023-06-21 at 11 43 21 AM](https://github.com/neurobagel/annotation_tool/assets/4140162/9fccfdcd-651b-4deb-9762-31f82a0f07ba)

### How to reproduce

Go to [annotate.neurobagel.org](annotate.neurobagel.org) and upload a participants.tsv (and optionally, a participants.json). Proceed to the categorization page.

### Anything else?

Fixed in by `bootstrap`/`bootstrap-vue` version rollback in commit https://github.com/neurobagel/annotation_tool/commit/7c71f42c49a51fc0878ef60d8f63fd94fc7daf30

**Comment by jarmoza** [comment] 2023-06-21 19:44
My initial suspicion was that this had something to do with the static site generation and deployment onto github pages.

However, after testing a few changes with `cd.yaml` (continuous deployment) and `nuxt.config.js` re: https://v2.nuxt.com/deployments/github-pages/, I took the educated guess that this might instead be related to our recent version bumps as pointed out by dependabot – the most directly related being `bootstrap` and `bootstrap-vue`.

After having reverted both to the previous versions, `4.6.1.` and `2.21.2`, respectively, this has now re-enabled the components on the categorization (and presumably on the annotation page as well would we have been able to access it).

**Comment by jarmoza** [comment] 2023-06-21 20:08
Further discussion on the incompatibility these package(s) and GitHub pages deployment will continue here: https://github.com/neurobagel/annotation_tool/issues/472

**Comment by surchs** [comment] 2023-06-28 14:01
> The tool functions locally via npm run dev and all e2e/component tests are green.

@jarmoza what happens locally when you run `npm run generate` and the test out the static page locally?

Could you also link the PR (or commit?) where you fixed this, please.

I think what we'd like here is to be able to create a test that fails when the user-facing behaviour is as described in the issue (i.e. without your fix / rollback applied). If the reason this fails is linked to difference of the testing and runtime environment, then I think we should make sure we test on the runtime environment.

**Comment by jarmoza** [comment] 2023-06-28 14:43
@surchs 

>what happens locally when you run npm run generate and the test out the static page locally

The site gets generated in `dist` as expected and you can run the annotation tool from there as long as you have a local server running. (I used a Python http server to test this.)

>Could you also link the PR (or commit?) where you fixed this, please.

[https://github.com/neurobagel/annotation_tool/commit/7c71f42c49a51fc0878ef60d8f63fd94fc7daf30](https://github.com/neurobagel/annotation_tool/commit/7c71f42c49a51fc0878ef60d8f63fd94fc7daf30)

>If the reason this fails is linked to difference of the testing and runtime environment, then I think we should make sure we >test on the runtime environment.

Can you provide a link to what you were referring to yesterday afternoon, re: runtime testing?

**Comment by surchs** [comment] 2023-06-28 15:01
> The site gets generated in dist as expected and you can run the annotation tool from there as long as you have a local server running.

Are you saying the site then behaves correctly for you? Because for me it does not:

```
➜ git show --oneline
edc0b49 (HEAD) Merge branch 'master' of https://github.com/neurobagel/annotation_tool
➜ npm run generate
➜ npm run start
```
leads to 

![image](https://github.com/neurobagel/annotation_tool/assets/1302022/b00b27b2-1ae7-4d97-96b8-d672b0d28acb)

for me 

> When you say test on the runtime environment are you referring to something like [Vercel](https://vercel.com/docs/concepts/deployments/preview-deployments) which you mentioned yesterday?

No, I meant that if we deploy the site in static mode and run the CD on github on the static site, then we should make sure we run out tests during local development also on the static site, and not on the live hosted site we get from `npm run dev` - I don't know if or how that works with Cypress. But I think it should.

Independently, we should have a test that fails given the breaking UI state on the static page so at least we know this won't come back

**Comment by jarmoza** [comment] 2023-06-28 15:32
👍 I just wasn't clear if you were trying to reproduce it working correctly in a local static deployment.

**Comment by surchs** [comment] 2023-06-28 15:40
ah yes. That was my intention indeed. If this is related to the way we access the app (i.e. either built as static or served live), then that is interesting. What I don't understand is why the static app runs well for you locally - but maybe I misunderstand and you were talking about the app running well after the fix?

**Comment by jarmoza** [comment] 2023-06-28 15:48
Let me rundown my original comment because it could use clearing up and as the perspective on this issue has matured a bit since writing it.

> My initial suspicion was that this had something to do with the static site generation and deployment onto github pages.

This is, in the end, correct. Before the package bumps (`bootstrap`/`boostrap-vue` is our current contention), the app was both running correctly via local manual and Cypress testing.

>However, after testing a few changes with cd.yaml (continuous deployment) and nuxt.config.js re: >https://v2.nuxt.com/deployments/github-pages/,

The testing here refers to on the repo/GitHub pages.

>I took the educated guess that this might instead be related to our recent version bumps as pointed out by dependabot – >the most directly related being bootstrap and bootstrap-vue.

It currently appears the issue has both to do with the package bump and the deployment. It's not an "either-or."

>After having reverted both to the previous versions, 4.6.1. and 2.21.2, respectively, this has now re-enabled the components >on the categorization page (and presumably on the annotation page as well would we have been able to access it).

I'm again referring to GitHub pages exclusively here.

>*Note: Changes were made to master as this was a deployment-side issue not testable locally.

Sounds like we _will_ be able to test it locally after all.

**Comment by jarmoza** [comment] 2023-07-05 23:07
@surchs There's some new information below regarding this issue, but I believe the resolution remains the same (for different reasons). Let me know your opinion though.

This issue initially began because we noticed that with the bump to Bootstrap 5 the category select table and column linking table on the categorization page were now unstyled (and we thought at the time, unclickable) thus breaking the workflow of the app deployed on Github pages

In fact, the latter is not the case. After having re-tested only scenarios listed below this evening to double check the resultant behavior, it is now known that the bump to Bootstrap 5 caused the same issue - unstyled table rows - but it did not break click behavior of the tables.

This means that regardless of the type of testing scenario:

1) non-static, local manual test
2) non-static, local cypress test
3) static, local manual test
4) static, local cypress test
5) GitHub cypress test
6) GitHub pages manual test (static)

they all produce this same behavior.

As to why this was not noticed other than the assumption of non-clickability once the Bootstrap 5 version was deployed, there is likely some mixup in the local package install as we were trying out the different versions/scenarios that led us to believe the "broken" behavior was not consistent

**Investigation:**

Part 1. 

a. The annotation tool was debugged across Bootstrap 4 and 5 in both static and non-static manual testing in the browser, as well as through the Cypress testing suite to see any differences between the HTML/CSS. The conclusion here was that somewhat inexplicably the styling introduced to the table by our code was being overridden by Bootstrap 5. The question as to why/how this was happening was unknown.
b. After concluding that there was an issue with the new version of Bootstrap, the currently supported version of Bootstrap for Bootstrap-Vue was located (and alongside it the most recent version of Bootstrap-Vue that the annotation tool should be using. As seen here (https://bootstrap-vue.org/docs), Bootstrap-Vue only supports up to Bootstrap 4.6.1, the version we had been using. And Bootstrap-Vue's latest version is 2.23.x.

Part 2.

a. After request from @surchs for more information about this issue, I reinvestigated the above scenarios and came to the conclusion that what is happening with the background coloring method for table rows in Bootstrap 5 that we were utilizing in Bootstrap-Vue/Bootstrap 4 does not appear to be supported. This is via the `tbody-tr-class` attribute on the `b-table` tag. If this feature is exclusive to Bootstrap-Vue, then the break in functionality would make sense since Bootstrap-Vue does not yet support Bootstrap 5 and Bootstrap 5 appears to use an updated implementation of the table widget. Specifically what was noticed through debugging is that Bootstrap applies an background color to the `td` underneath the `tr` tag via scss.
b. Furthermore, click behavior remains enabled on the tables of the categorization page and this explains why - though we didn't notice it was enabled in manual testing on the deployed tool - all of the Cypress tests were able to pass through the page. After all, the current tests (and component behavior) does not rely on the background color of the rows to proceed.

**Conclusion:** Until such time that Bootstrap-Vue supports Bootstrap 5, it is likely not a wise idea to proceed past its highest supported version of Bootstrap (4.6.1, in this case). However, bumping Bootstrap-Vue up to its latest version (2.23.1, in this case) is not only acceptable, but it would be advisable to do so.

**Comment by surchs** [comment] 2023-07-06 03:50
Thanks for the writeup @jarmoza. I think it's important that we learn something from this, especially after you have invested so much time. Personally, I'm less concerned about the Bootstrap major version breaking things (that part actually makes sense given semver) and more about the fact that nothing automatic alerted us about the fact that things were breaking. 

Applying and changing color in response to user actions is central to the user workflow of our app at the moment, and the app is not usable if this type of styling is broken. 

> the current tests do not rely on the background color of the rows to proceed

Yes, exactly. I think the first lesson here is: we didn't test (enough of) the crucial parts of our app, i.e. we didn't test the color. That was no good, and we need to test it.


> If we would like to write a test here, it would be to see if the td underlying the tr tag actually uses the background color(s) we expect.

Agreed! The reason I had asked you to explain what you had found so far in your investigation was that I wanted to understand if you have found some reason that we **cannot** write such a test or that it would be extremely cumbersome. Based on what you describe and on a bit of research on my own, I think that's not the case, i.e. we can pretty easily write a test for color in response to user action.

The most basic version might just be to assert "before click -> background is white; after click -> background is not white"
A less brittle but also more involved version would be to assert "before click -> background is different than after click". The latter is possible, but not as readable. E.g. something that works at the end of the `categorization-pagetest.cy.js`:

```javascript
// Make sure the color changes after clicking
cy.get("[data-cy='column-linking-table'] tbody > tr")
.contains(p_dataset["category_columns"]["Subject ID"][0])
.parent().invoke('css', 'background-color')
.then((old_color) => {
    cy.categorizeColumn("Subject ID", p_dataset["category_columns"]["Subject ID"][0])
    cy.get("[data-cy='column-linking-table'] tbody > tr")
        .contains(p_dataset["category_columns"]["Subject ID"][0]).parent()
        .should('not.have.css', 'background-color', old_color);
}
);
```

So the second takeaway for me here is: when we find a bug that breaks our app, we need to find out how we can write a regression test for this bug, even if fixing the bug directly is trivial but writing the regression test is hard.

>  there was likely some mixup in the local package install as we were trying out the different versions/scenarios that led us to believe the "broken" behavior was not consistent

That makes sense to me. The third lesson I would draw from this is: it's important that the issue description is clear and reproducible, especially when a bug is "weird" like here, e.g. when it "sometimes isn't there". It'll take some time to go through these steps to get this clarity, but it'll avoid us going on a bunch of snipe hunts that will take substantially longer. I also think that over time we'll build better intuition on why things are weird and so save more time.

The last lesson I'll draw here is: we need test environments and preview builds that are as close to what we deploy publicly as possible. That means: when developing locally, we should run the tests on the static generated app. Because that is cumbersome (first must generate, second must run tests), we should make that step automatic - probably as part of our pre-commit checks. For the preview builds, we now have https://github.com/neurobagel/project/issues/135 to build previews with netlify. We should see if that's close enough to our public GH pages deployment to catch things like this. If it isn't, we should switch the public deployment to also be on netlify. In either case, we should not use master as a substitute for these tools to test things (e.g. https://github.com/neurobagel/annotation_tool/commit/cf3032947ae8c3921a4d143533fd12b9788e59e2) - even if it is temporary and there are most likely no active users at that moment. If we need to check a "close to prod" deployment, use a temp branch and then the preview deployments.

So I think this uncovered a couple of important lessons for us, and that's great. To close this issue now, we need to write at least one test that

- fails when the app is checked out to `edc0b49dd6c63eaef3d61436f5fa87e6885c6b08`, i.e. to before the Bootstrap major version rollback / fix
- passes with the rollback-fix applied (i.e. on current master).

**Comment by jarmoza** [comment] 2023-07-06 14:37
@surchs Excellent feedback, and I agree that there are several good lessons to take away from this issue, our handling of it, and its resolution.

One other lesson to add, that I think is necessary is a reminder of something we have talked about previously. In addition as a place for reporting issues, resolutions, and discussion, GitHub issues should also be thought of as diaristic, that is, a place to record notes as an investigation of an issue is ongoing.

Specifically with regard to the discussion and my notes above, much of my recapitulation of the investigation of this issue is from memory – and while that maybe speaks as a compliment to my memory it is much preferable to rely on a daily account of an investigation if it is not closed by end of day.

I will go about writing the test(s) in question today and notify you when finished.

**Closed** 2023-07-11 18:36 UTC
Labels: importance:urgent, type:bug
